//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Service.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotifierMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotifierMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pharmacy.Service.Resource.NotifierMessage", typeof(NotifierMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، سفارش شما در {0} مورد پذیرش قرار گرفته است، لطفا جهت ادامه فرایند سفارش، از طریق لینک زیر هزینه ارسال را پرداخت نمایید:
        ///{1}.
        /// </summary>
        public static string DrugStoreAcceptOrder {
            get {
                return ResourceManager.GetString("DrugStoreAcceptOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید ثبت نام در فارما:
        ///{0}.
        /// </summary>
        public static string MobileConfirmMessage {
            get {
                return ResourceManager.GetString("MobileConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، سفارش به شماره {0} لغو گردید.
        /// </summary>
        public static string OrderCanceled {
            get {
                return ResourceManager.GetString("OrderCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، سفارش به شماره {0} ثبت شد و پس از بررسی از طریق پیامک به اطلاع شما خواهد رسید.
        /// </summary>
        public static string OrderPayment {
            get {
                return ResourceManager.GetString("OrderPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی {0}، ثبت نام شما با موفقیت انجام شد،
        ///فارما.
        /// </summary>
        public static string SignUpMessage {
            get {
                return ResourceManager.GetString("SignUpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی فارما، نسخه شما بررسی گردید، جهت پرداخت هزینه آن از طریق لینک زیر اقدام نمایید:
        ///{0}.
        /// </summary>
        public static string TempBasketUrl {
            get {
                return ResourceManager.GetString("TempBasketUrl", resourceCulture);
            }
        }
    }
}
